# Generated by Django 5.2.8 on 2026-01-08 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_number', models.IntegerField()),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=10)),
                ('min_range', models.IntegerField(default=1)),
                ('max_range', models.IntegerField(default=100)),
                ('is_won', models.BooleanField(default=False)),
                ('is_finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuessHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess_number', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='num_guess_app.game')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
